#this file is for new customer registration

import cust_login as cust

def signup(user_id,password,user_details): #signup function
    print('\n_____Enter the following details_____')
    name = input('enter your name: ').strip().lower()
    age = int(input('enter your age: '))
    gen = input('enter your gender (male/female/others): ')
    p_no = int(input('enter 10-digit mobile no.: '))
    adrs = input('enter your address (city_name - pin_code): ')
    bal = int(input('enter starting amount: '))
    pwd = input('set your account password: ')
    new_id = int(user_id[-1])+1
    print('\nCongratulations!! Your account has been successfully created\nYour user id is automatically generated by the system')
    print(f'your used id is: {new_id}\nkindly note it down for future reference')
    add_data(user_id,password,user_details,name,age,gen,p_no,adrs,bal,pwd,str(new_id))


def add_data(user_id,password,user_details,*var): #length of var = 8/ This function adds new user data to the existing data structures
    user_details[str(var[7])] = {'name':var[0],'age':var[1],'gender':var[2],
                                 'phone':var[3],'address':var[4],'balance':var[5]}
    password.append(var[6])
    user_id.append(var[7])
    pos = len(user_id) - 1
    cust.login_menu(user_id,str(var[7]),password,pos,user_details)